project:
  type: website
  output-dir: docs

website:
  title: "Aneesh Agarwal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AneeshAgarwala
      - icon: linkedin
        href: https://www.linkedin.com/in/aneesh-agarwal-0b5755201/

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css



